pytest and PyNEST discovery

diff --git a/testsuite/do_tests.sh.in b/testsuite/do_tests.sh.in
--- a/testsuite/do_tests.sh.in
+++ b/testsuite/do_tests.sh.in
@@ -40,15 +40,10 @@ EOF
     exit $1
 }
 
-TEST_PYNEST=false
-
 while test $# -gt 0 ; do
     case "$1" in
         --help)
             usage 0
-            ;;
-        --test-pynest)
-            TEST_PYNEST=true
             ;;
         --output-dir=*)
             TEST_OUTDIR="$( echo "$1" | sed 's/^--output-dir=//' )"
@@ -235,7 +230,7 @@ junit_close ()
 #   and strings describing the exit code.
 #
 #   If any of the variables CODES_SUCCESS, CODES_SKIPPED or CODES_FAILURE
-#   contain an entry for the exit code, the respective string is logged, 
+#   contain an entry for the exit code, the respective string is logged,
 #   and the test is either counted as passed or failed.
 #
 #   If none of the variables CODES_SUCCESS, CODES_SKIPPED or CODES_FAILURE
@@ -350,7 +345,6 @@ run_test ()
 # Set environment variables.
 # The NEST_ variants of the global variables were set by
 # cmake during configuration.
-export PYTHONPATH=$NEST_PYTHONPATH:$PYTHONPATH
 export PATH=$NEST_PATH:$PATH
 
 # Gather some information about the host
@@ -437,6 +431,26 @@ CODES_SKIPPED=\
 ' 203 Skipped (Threading required),'\
 ' 204 Skipped (GSL required),'\
 ' 205 Skipped (MUSIC required),'
+
+echo
+echo 'Phase 0: Python configuration notice'
+echo '------------------------------------'
+echo "  env PYTHON = `which ${PYTHON}`"
+
+if test -n "$PYTHON" ; then
+    ${PYTHON} -c "from __future__ import print_function; import nest; import sys; print(sys.modules['nest'].__path__[0], file=sys.stderr)" > /dev/null 2> tmp_python_path
+    TEST_PYNEST=$?
+    py_install_path=`head -n1 tmp_python_path`
+    rm tmp_python_path
+
+    if test "x${TEST_PYNEST}" = x0 ; then
+        echo "  Found PyNEST installation at: ${py_install_path}"
+        echo "  Will try to run the PyNEST unittests!"
+    else
+        echo "  No PyNEST installation found!"
+        echo "  Will not run the PyNEST unittests!"
+    fi
+fi
 
 echo
 echo 'Phase 1: Testing if SLI can execute scripts and report errors'
@@ -703,13 +717,13 @@ else
 fi
 
 
-if test "x${TEST_PYNEST}" = xtrue ; then
+if test "x${TEST_PYNEST}" = x0 ; then
 
     echo
     echo "Phase 7: Running PyNEST tests."
     echo "------------------------------"
-    
-    # If possible, we run using nosetests. To find out if nosetests work, 
+
+    # If possible, we run using nosetests. To find out if nosetests work,
     # we proceed in two steps:
     # 1. Check if nosetests is available
     # 2. Check that nosetests supports --with-xunit by running nosetests.
@@ -718,19 +732,20 @@ if test "x${TEST_PYNEST}" = xtrue ; then
     #    of support for nosetests. We use the TEST_OUTDIR as Python-free
     #    dummy directory to search for tests.
 
-    if command -v @NOSETESTS@ >/dev/null 2>&1 && @PYTHON@ @NOSETESTS@ --with-xunit --xunit-file=/dev/null --where=${TEST_OUTDIR} >/dev/null 2>&1; then
+    if command -v pytest >/dev/null 2>&1 ; then
 
         echo
-        echo "  Using nosetests."
+        echo "  Using pytest."
         echo
 
-        @PYTHON@ @NOSETESTS@ -v --with-xunit --xunit-file=${TEST_OUTDIR}/pynest_tests.xml ${NEST_PYTHON_PREFIX:-@CMAKE_INSTALL_PREFIX@/@PYEXECDIR@}/nest/tests ${NEST_PYTHON_PREFIX:-@CMAKE_INSTALL_PREFIX@/@PYEXECDIR@}/nest/topology/tests 2>&1 \
-            | tee -a "${TEST_LOGFILE}" | grep -i --line-buffered "\.\.\. ok\|fail\|skip\|error" | sed 's/^/  /'
+        pytest -vvv --junitxml=${TEST_OUTDIR}/pynest_tests.xml ${py_install_path} | tee -a ${TEST_LOGFILE}
 
-        PYNEST_TEST_TOTAL="$(  tail -n 3 ${TEST_LOGFILE} | grep Ran | cut -d' ' -f2 )"
-        PYNEST_TEST_SKIPPED="$(  tail -n 1 ${TEST_LOGFILE} | sed -$EXTENDED_REGEX_PARAM 's/.*SKIP=([0-9]+).*/\1/')"
-        PYNEST_TEST_FAILURES="$( tail -n 3 ${TEST_LOGFILE} | grep \( | sed -$EXTENDED_REGEX_PARAM 's/^[a-zA-Z]+ \((.*)\)/\1/' | sed -$EXTENDED_REGEX_PARAM 's/.*failures=([0-9]+).*/\1/' )"
-        PYNEST_TEST_ERRORS="$( tail -n 3 ${TEST_LOGFILE} | grep \( | sed -$EXTENDED_REGEX_PARAM 's/^[a-zA-Z]+ \((.*)\)/\1/' | sed -$EXTENDED_REGEX_PARAM 's/.*errors=([0-9]+).*/\1/' )"
+        result_line="$(  tail -n 3 ${TEST_LOGFILE} | grep '=====')"
+        PYNEST_TEST_FAILURES=`echo $result_line | sed -$EXTENDED_REGEX_PARAM 's/.* ([0-9]+) failed.*/\1/'`
+        PYNEST_TEST_ERRORS=`echo $result_line | sed -$EXTENDED_REGEX_PARAM 's/.* ([0-9]+) error.*/\1/'`
+        PYNEST_TEST_SKIPPED=`echo $result_line | sed -$EXTENDED_REGEX_PARAM 's/.* ([0-9]+) skipped.*/\1/'`
+        PYNEST_TEST_WARNINGS=`echo $result_line | sed -$EXTENDED_REGEX_PARAM 's/.* ([0-9]+) warnings.*/\1/'`
+        PYNEST_TEST_PASSED=`echo $result_line | sed -$EXTENDED_REGEX_PARAM 's/.* ([0-9]+) passed.*/\1/'`
 
         # check that PYNEST_TEST_FAILURES/PYNEST_TEST_ERRORS contain numbers
         if test ${PYNEST_TEST_FAILURES} -eq ${PYNEST_TEST_FAILURES} 2>/dev/null ; then
@@ -751,9 +766,21 @@ if test "x${TEST_PYNEST}" = xtrue ; then
         else
           PYNEST_TEST_SKIPPED=0
         fi
+        if test ${PYNEST_TEST_WARNINGS} -eq ${PYNEST_TEST_WARNINGS} 2>/dev/null ; then
+          # PYNEST_TEST_WARNINGS is a valid number
+          :
+        else
+          PYNEST_TEST_WARNINGS=0
+        fi
+        if test ${PYNEST_TEST_PASSED} -eq ${PYNEST_TEST_PASSED} 2>/dev/null ; then
+          # PYNEST_TEST_PASSED is a valid number
+          :
+        else
+          PYNEST_TEST_PASSED=0
+        fi
         PYNEST_TEST_FAILED=$(($PYNEST_TEST_ERRORS + $PYNEST_TEST_FAILURES))
         PYNEST_TEST_PASSED=$(($PYNEST_TEST_TOTAL - $PYNEST_TEST_SKIPPED - $PYNEST_TEST_FAILED))
-
+        PYNEST_TEST_TOTAL=$(($PYNEST_TEST_FAILURES + $PYNEST_TEST_ERRORS + $PYNEST_TEST_SKIPPED + $PYNEST_TEST_PASSED))
     else
 
         echo
@@ -767,9 +794,9 @@ if test "x${TEST_PYNEST}" = xtrue ; then
         PYNEST_TEST_PASSED="$( cat pynest_test_numbers.log | cut -d' ' -f2 )"
         PYNEST_TEST_SKIPPED="$( cat pynest_test_numbers.log | cut -d' ' -f3 )"
         PYNEST_TEST_FAILED="$( cat pynest_test_numbers.log | cut -d' ' -f4 )"
+        PYNEST_TEST_WARNINGS="0"
 
         rm -f "pynest_test_numbers.log"
-
     fi
 
     echo
@@ -777,6 +804,7 @@ if test "x${TEST_PYNEST}" = xtrue ; then
     echo "     Passed: ${PYNEST_TEST_PASSED}"
     echo "     Skipped: ${PYNEST_TEST_SKIPPED}"
     echo "     Failed: ${PYNEST_TEST_FAILED}"
+    echo "     Warnings: ${PYNEST_TEST_WARNINGS}"
 
     PYNEST_TEST_SKIPPED_TEXT="(${PYNEST_TEST_SKIPPED} PyNEST)"
     PYNEST_TEST_FAILED_TEXT="(${PYNEST_TEST_FAILED} PyNEST)"
